sudo: required
services:
  - docker
before_install:
  - docker pull badi/cloudmesh_classes
script:
  - docker run -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) -v $PWD:/data -it --rm badi/cloudmesh_classes make
